/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;
import org.openapis.openapi.utils.LazySingletonValue;
import org.openapis.openapi.utils.Utils;
/**
 * ActivateAWorkflowResponseBody - 200
 */

public class ActivateAWorkflowResponseBody {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("activated")
    private Optional<? extends Boolean> activated;

    @JsonCreator
    public ActivateAWorkflowResponseBody(
            @JsonProperty("activated") Optional<? extends Boolean> activated) {
        Utils.checkNotNull(activated, "activated");
        this.activated = activated;
    }
    
    public ActivateAWorkflowResponseBody() {
        this(Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Boolean> activated() {
        return (Optional<Boolean>) activated;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public ActivateAWorkflowResponseBody withActivated(boolean activated) {
        Utils.checkNotNull(activated, "activated");
        this.activated = Optional.ofNullable(activated);
        return this;
    }

    public ActivateAWorkflowResponseBody withActivated(Optional<? extends Boolean> activated) {
        Utils.checkNotNull(activated, "activated");
        this.activated = activated;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ActivateAWorkflowResponseBody other = (ActivateAWorkflowResponseBody) o;
        return 
            java.util.Objects.deepEquals(this.activated, other.activated);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            activated);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ActivateAWorkflowResponseBody.class,
                "activated", activated);
    }
    
    public final static class Builder {
 
        private Optional<? extends Boolean> activated;  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder activated(boolean activated) {
            Utils.checkNotNull(activated, "activated");
            this.activated = Optional.ofNullable(activated);
            return this;
        }

        public Builder activated(Optional<? extends Boolean> activated) {
            Utils.checkNotNull(activated, "activated");
            this.activated = activated;
            return this;
        }
        
        public ActivateAWorkflowResponseBody build() {
            if (activated == null) {
                activated = _SINGLETON_VALUE_Activated.value();
            }
            return new ActivateAWorkflowResponseBody(
                activated);
        }

        private static final LazySingletonValue<Optional<? extends Boolean>> _SINGLETON_VALUE_Activated =
                new LazySingletonValue<>(
                        "activated",
                        "true",
                        new TypeReference<Optional<? extends Boolean>>() {});
    }
}

