/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.core.type.TypeReference;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Optional;
import java.util.stream.Stream;
import org.openapis.openapi.models.errors.SDKError;
import org.openapis.openapi.utils.LazySingletonValue;
import org.openapis.openapi.utils.Utils;
import org.openapitools.jackson.nullable.JsonNullable;


public class CreateACredentialRequestBuilder {

    private Optional<? extends CreateACredentialRequestBody> request = Optional.empty();
    private final SDKMethodInterfaces.MethodCallCreateACredential sdk;

    public CreateACredentialRequestBuilder(SDKMethodInterfaces.MethodCallCreateACredential sdk) {
        this.sdk = sdk;
    }
                
    public CreateACredentialRequestBuilder request(CreateACredentialRequestBody request) {
        Utils.checkNotNull(request, "request");
        this.request = Optional.of(request);
        return this;
    }

    public CreateACredentialRequestBuilder request(Optional<? extends CreateACredentialRequestBody> request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public CreateACredentialResponse call() throws Exception {

        return sdk.createACredential(
            request);
    }
}
