/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;
import org.openapis.openapi.utils.LazySingletonValue;
import org.openapis.openapi.utils.Utils;
/**
 * CreateACredentialResponseBody - 200
 */

public class CreateACredentialResponseBody {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("success")
    private Optional<? extends Boolean> success;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("credentialId")
    private Optional<? extends String> credentialId;

    @JsonCreator
    public CreateACredentialResponseBody(
            @JsonProperty("success") Optional<? extends Boolean> success,
            @JsonProperty("credentialId") Optional<? extends String> credentialId) {
        Utils.checkNotNull(success, "success");
        Utils.checkNotNull(credentialId, "credentialId");
        this.success = success;
        this.credentialId = credentialId;
    }
    
    public CreateACredentialResponseBody() {
        this(Optional.empty(), Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Boolean> success() {
        return (Optional<Boolean>) success;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<String> credentialId() {
        return (Optional<String>) credentialId;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public CreateACredentialResponseBody withSuccess(boolean success) {
        Utils.checkNotNull(success, "success");
        this.success = Optional.ofNullable(success);
        return this;
    }

    public CreateACredentialResponseBody withSuccess(Optional<? extends Boolean> success) {
        Utils.checkNotNull(success, "success");
        this.success = success;
        return this;
    }

    public CreateACredentialResponseBody withCredentialId(String credentialId) {
        Utils.checkNotNull(credentialId, "credentialId");
        this.credentialId = Optional.ofNullable(credentialId);
        return this;
    }

    public CreateACredentialResponseBody withCredentialId(Optional<? extends String> credentialId) {
        Utils.checkNotNull(credentialId, "credentialId");
        this.credentialId = credentialId;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateACredentialResponseBody other = (CreateACredentialResponseBody) o;
        return 
            java.util.Objects.deepEquals(this.success, other.success) &&
            java.util.Objects.deepEquals(this.credentialId, other.credentialId);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            success,
            credentialId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateACredentialResponseBody.class,
                "success", success,
                "credentialId", credentialId);
    }
    
    public final static class Builder {
 
        private Optional<? extends Boolean> success;
 
        private Optional<? extends String> credentialId = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder success(boolean success) {
            Utils.checkNotNull(success, "success");
            this.success = Optional.ofNullable(success);
            return this;
        }

        public Builder success(Optional<? extends Boolean> success) {
            Utils.checkNotNull(success, "success");
            this.success = success;
            return this;
        }

        public Builder credentialId(String credentialId) {
            Utils.checkNotNull(credentialId, "credentialId");
            this.credentialId = Optional.ofNullable(credentialId);
            return this;
        }

        public Builder credentialId(Optional<? extends String> credentialId) {
            Utils.checkNotNull(credentialId, "credentialId");
            this.credentialId = credentialId;
            return this;
        }
        
        public CreateACredentialResponseBody build() {
            if (success == null) {
                success = _SINGLETON_VALUE_Success.value();
            }
            return new CreateACredentialResponseBody(
                success,
                credentialId);
        }

        private static final LazySingletonValue<Optional<? extends Boolean>> _SINGLETON_VALUE_Success =
                new LazySingletonValue<>(
                        "success",
                        "true",
                        new TypeReference<Optional<? extends Boolean>>() {});
    }
}

