/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.core.type.TypeReference;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Optional;
import java.util.stream.Stream;
import org.openapis.openapi.models.errors.SDKError;
import org.openapis.openapi.utils.LazySingletonValue;
import org.openapis.openapi.utils.Utils;
import org.openapitools.jackson.nullable.JsonNullable;


public class CredentialMedataByAppRequestBuilder {

    private String app;
    private final SDKMethodInterfaces.MethodCallCredentialMedataByApp sdk;

    public CredentialMedataByAppRequestBuilder(SDKMethodInterfaces.MethodCallCredentialMedataByApp sdk) {
        this.sdk = sdk;
    }

    public CredentialMedataByAppRequestBuilder app(String app) {
        Utils.checkNotNull(app, "app");
        this.app = app;
        return this;
    }

    public CredentialMedataByAppResponse call() throws Exception {

        return sdk.credentialMedataByApp(
            app);
    }
}
