/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

public class DeactivateAWorkflowRequestBody {

    /**
     * The Id of the user you want to lookup. Returned from the Create User endpoint. Note: you can also use the Embedded user's `username` in this field.
     */
    @JsonProperty("userId")
    private String userId;

    /**
     * The Id of the workflow to activate. If you pass this parameter, then `workflowName` is not required.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("workflowId")
    private Optional<? extends String> workflowId;

    /**
     * The name of the workflow to activate.  If you pass this parameter, then `workflowId` is not required.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("workflowName")
    private Optional<? extends String> workflowName;

    @JsonCreator
    public DeactivateAWorkflowRequestBody(
            @JsonProperty("userId") String userId,
            @JsonProperty("workflowId") Optional<? extends String> workflowId,
            @JsonProperty("workflowName") Optional<? extends String> workflowName) {
        Utils.checkNotNull(userId, "userId");
        Utils.checkNotNull(workflowId, "workflowId");
        Utils.checkNotNull(workflowName, "workflowName");
        this.userId = userId;
        this.workflowId = workflowId;
        this.workflowName = workflowName;
    }
    
    public DeactivateAWorkflowRequestBody(
            String userId) {
        this(userId, Optional.empty(), Optional.empty());
    }

    /**
     * The Id of the user you want to lookup. Returned from the Create User endpoint. Note: you can also use the Embedded user's `username` in this field.
     */
    @JsonIgnore
    public String userId() {
        return userId;
    }

    /**
     * The Id of the workflow to activate. If you pass this parameter, then `workflowName` is not required.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<String> workflowId() {
        return (Optional<String>) workflowId;
    }

    /**
     * The name of the workflow to activate.  If you pass this parameter, then `workflowId` is not required.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<String> workflowName() {
        return (Optional<String>) workflowName;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * The Id of the user you want to lookup. Returned from the Create User endpoint. Note: you can also use the Embedded user's `username` in this field.
     */
    public DeactivateAWorkflowRequestBody withUserId(String userId) {
        Utils.checkNotNull(userId, "userId");
        this.userId = userId;
        return this;
    }

    /**
     * The Id of the workflow to activate. If you pass this parameter, then `workflowName` is not required.
     */
    public DeactivateAWorkflowRequestBody withWorkflowId(String workflowId) {
        Utils.checkNotNull(workflowId, "workflowId");
        this.workflowId = Optional.ofNullable(workflowId);
        return this;
    }

    /**
     * The Id of the workflow to activate. If you pass this parameter, then `workflowName` is not required.
     */
    public DeactivateAWorkflowRequestBody withWorkflowId(Optional<? extends String> workflowId) {
        Utils.checkNotNull(workflowId, "workflowId");
        this.workflowId = workflowId;
        return this;
    }

    /**
     * The name of the workflow to activate.  If you pass this parameter, then `workflowId` is not required.
     */
    public DeactivateAWorkflowRequestBody withWorkflowName(String workflowName) {
        Utils.checkNotNull(workflowName, "workflowName");
        this.workflowName = Optional.ofNullable(workflowName);
        return this;
    }

    /**
     * The name of the workflow to activate.  If you pass this parameter, then `workflowId` is not required.
     */
    public DeactivateAWorkflowRequestBody withWorkflowName(Optional<? extends String> workflowName) {
        Utils.checkNotNull(workflowName, "workflowName");
        this.workflowName = workflowName;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DeactivateAWorkflowRequestBody other = (DeactivateAWorkflowRequestBody) o;
        return 
            java.util.Objects.deepEquals(this.userId, other.userId) &&
            java.util.Objects.deepEquals(this.workflowId, other.workflowId) &&
            java.util.Objects.deepEquals(this.workflowName, other.workflowName);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            userId,
            workflowId,
            workflowName);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DeactivateAWorkflowRequestBody.class,
                "userId", userId,
                "workflowId", workflowId,
                "workflowName", workflowName);
    }
    
    public final static class Builder {
 
        private String userId;
 
        private Optional<? extends String> workflowId = Optional.empty();
 
        private Optional<? extends String> workflowName = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The Id of the user you want to lookup. Returned from the Create User endpoint. Note: you can also use the Embedded user's `username` in this field.
         */
        public Builder userId(String userId) {
            Utils.checkNotNull(userId, "userId");
            this.userId = userId;
            return this;
        }

        /**
         * The Id of the workflow to activate. If you pass this parameter, then `workflowName` is not required.
         */
        public Builder workflowId(String workflowId) {
            Utils.checkNotNull(workflowId, "workflowId");
            this.workflowId = Optional.ofNullable(workflowId);
            return this;
        }

        /**
         * The Id of the workflow to activate. If you pass this parameter, then `workflowName` is not required.
         */
        public Builder workflowId(Optional<? extends String> workflowId) {
            Utils.checkNotNull(workflowId, "workflowId");
            this.workflowId = workflowId;
            return this;
        }

        /**
         * The name of the workflow to activate.  If you pass this parameter, then `workflowId` is not required.
         */
        public Builder workflowName(String workflowName) {
            Utils.checkNotNull(workflowName, "workflowName");
            this.workflowName = Optional.ofNullable(workflowName);
            return this;
        }

        /**
         * The name of the workflow to activate.  If you pass this parameter, then `workflowId` is not required.
         */
        public Builder workflowName(Optional<? extends String> workflowName) {
            Utils.checkNotNull(workflowName, "workflowName");
            this.workflowName = workflowName;
            return this;
        }
        
        public DeactivateAWorkflowRequestBody build() {
            return new DeactivateAWorkflowRequestBody(
                userId,
                workflowId,
                workflowName);
        }
    }
}

