/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;

public class DeleteACredentialRequest {

    /**
     * The credential you're looking to delete
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=credentialId")
    private String credentialId;

    /**
     * The Id of the user associated with this credential
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=userId")
    private String userId;

    @JsonCreator
    public DeleteACredentialRequest(
            String credentialId,
            String userId) {
        Utils.checkNotNull(credentialId, "credentialId");
        Utils.checkNotNull(userId, "userId");
        this.credentialId = credentialId;
        this.userId = userId;
    }

    /**
     * The credential you're looking to delete
     */
    @JsonIgnore
    public String credentialId() {
        return credentialId;
    }

    /**
     * The Id of the user associated with this credential
     */
    @JsonIgnore
    public String userId() {
        return userId;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * The credential you're looking to delete
     */
    public DeleteACredentialRequest withCredentialId(String credentialId) {
        Utils.checkNotNull(credentialId, "credentialId");
        this.credentialId = credentialId;
        return this;
    }

    /**
     * The Id of the user associated with this credential
     */
    public DeleteACredentialRequest withUserId(String userId) {
        Utils.checkNotNull(userId, "userId");
        this.userId = userId;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DeleteACredentialRequest other = (DeleteACredentialRequest) o;
        return 
            java.util.Objects.deepEquals(this.credentialId, other.credentialId) &&
            java.util.Objects.deepEquals(this.userId, other.userId);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            credentialId,
            userId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DeleteACredentialRequest.class,
                "credentialId", credentialId,
                "userId", userId);
    }
    
    public final static class Builder {
 
        private String credentialId;
 
        private String userId;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The credential you're looking to delete
         */
        public Builder credentialId(String credentialId) {
            Utils.checkNotNull(credentialId, "credentialId");
            this.credentialId = credentialId;
            return this;
        }

        /**
         * The Id of the user associated with this credential
         */
        public Builder userId(String userId) {
            Utils.checkNotNull(userId, "userId");
            this.userId = userId;
            return this;
        }
        
        public DeleteACredentialRequest build() {
            return new DeleteACredentialRequest(
                credentialId,
                userId);
        }
    }
}

