/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;
/**
 * GenerateJwtTokenResponseBody - 200
 */

public class GenerateJwtTokenResponseBody {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("token")
    private Optional<? extends String> token;

    @JsonCreator
    public GenerateJwtTokenResponseBody(
            @JsonProperty("token") Optional<? extends String> token) {
        Utils.checkNotNull(token, "token");
        this.token = token;
    }
    
    public GenerateJwtTokenResponseBody() {
        this(Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<String> token() {
        return (Optional<String>) token;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public GenerateJwtTokenResponseBody withToken(String token) {
        Utils.checkNotNull(token, "token");
        this.token = Optional.ofNullable(token);
        return this;
    }

    public GenerateJwtTokenResponseBody withToken(Optional<? extends String> token) {
        Utils.checkNotNull(token, "token");
        this.token = token;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GenerateJwtTokenResponseBody other = (GenerateJwtTokenResponseBody) o;
        return 
            java.util.Objects.deepEquals(this.token, other.token);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            token);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GenerateJwtTokenResponseBody.class,
                "token", token);
    }
    
    public final static class Builder {
 
        private Optional<? extends String> token = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder token(String token) {
            Utils.checkNotNull(token, "token");
            this.token = Optional.ofNullable(token);
            return this;
        }

        public Builder token(Optional<? extends String> token) {
            Utils.checkNotNull(token, "token");
            this.token = token;
            return this;
        }
        
        public GenerateJwtTokenResponseBody build() {
            return new GenerateJwtTokenResponseBody(
                token);
        }
    }
}

