/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.core.type.TypeReference;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Optional;
import java.util.stream.Stream;
import org.openapis.openapi.models.errors.SDKError;
import org.openapis.openapi.utils.LazySingletonValue;
import org.openapis.openapi.utils.Utils;
import org.openapitools.jackson.nullable.JsonNullable;


public class GetAnIntegrationRequestBuilder {

    private String integrationId;
    private String userId;
    private final SDKMethodInterfaces.MethodCallGetAnIntegration sdk;

    public GetAnIntegrationRequestBuilder(SDKMethodInterfaces.MethodCallGetAnIntegration sdk) {
        this.sdk = sdk;
    }

    public GetAnIntegrationRequestBuilder integrationId(String integrationId) {
        Utils.checkNotNull(integrationId, "integrationId");
        this.integrationId = integrationId;
        return this;
    }

    public GetAnIntegrationRequestBuilder userId(String userId) {
        Utils.checkNotNull(userId, "userId");
        this.userId = userId;
        return this;
    }

    public GetAnIntegrationResponse call() throws Exception {

        return sdk.getAnIntegration(
            integrationId,
            userId);
    }
}
