/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;

public class GetWorkflowAnalyticsRequest {

    /**
     * The Id of the workflow you want to find errors for
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=workflowId")
    private String workflowId;

    @JsonCreator
    public GetWorkflowAnalyticsRequest(
            String workflowId) {
        Utils.checkNotNull(workflowId, "workflowId");
        this.workflowId = workflowId;
    }

    /**
     * The Id of the workflow you want to find errors for
     */
    @JsonIgnore
    public String workflowId() {
        return workflowId;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * The Id of the workflow you want to find errors for
     */
    public GetWorkflowAnalyticsRequest withWorkflowId(String workflowId) {
        Utils.checkNotNull(workflowId, "workflowId");
        this.workflowId = workflowId;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetWorkflowAnalyticsRequest other = (GetWorkflowAnalyticsRequest) o;
        return 
            java.util.Objects.deepEquals(this.workflowId, other.workflowId);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            workflowId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetWorkflowAnalyticsRequest.class,
                "workflowId", workflowId);
    }
    
    public final static class Builder {
 
        private String workflowId;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The Id of the workflow you want to find errors for
         */
        public Builder workflowId(String workflowId) {
            Utils.checkNotNull(workflowId, "workflowId");
            this.workflowId = workflowId;
            return this;
        }
        
        public GetWorkflowAnalyticsRequest build() {
            return new GetWorkflowAnalyticsRequest(
                workflowId);
        }
    }
}

