/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.core.type.TypeReference;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Optional;
import java.util.stream.Stream;
import org.openapis.openapi.models.errors.SDKError;
import org.openapis.openapi.utils.LazySingletonValue;
import org.openapis.openapi.utils.Utils;
import org.openapitools.jackson.nullable.JsonNullable;


public class GetWorkflowErrorsRequestBuilder {

    private String workflowId;
    private Optional<? extends String> userId = Optional.empty();
    private final SDKMethodInterfaces.MethodCallGetWorkflowErrors sdk;

    public GetWorkflowErrorsRequestBuilder(SDKMethodInterfaces.MethodCallGetWorkflowErrors sdk) {
        this.sdk = sdk;
    }

    public GetWorkflowErrorsRequestBuilder workflowId(String workflowId) {
        Utils.checkNotNull(workflowId, "workflowId");
        this.workflowId = workflowId;
        return this;
    }
                
    public GetWorkflowErrorsRequestBuilder userId(String userId) {
        Utils.checkNotNull(userId, "userId");
        this.userId = Optional.of(userId);
        return this;
    }

    public GetWorkflowErrorsRequestBuilder userId(Optional<? extends String> userId) {
        Utils.checkNotNull(userId, "userId");
        this.userId = userId;
        return this;
    }

    public GetWorkflowErrorsResponse call() throws Exception {

        return sdk.getWorkflowErrors(
            workflowId,
            userId);
    }
}
