/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;
import org.openapis.openapi.utils.SpeakeasyMetadata;
import org.openapis.openapi.utils.Utils;

public class ListWorkflowsRequest {

    /**
     * This parameter allows you to filter workflows based on the name of the integration you're looking for. For example, if you were looking for a Shopify integration, specify shopify
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=integration")
    private Optional<? extends String> integration;

    /**
     * The Id of the user you want to lookup. Returned from the Create User endpoint. Note: you can also use the Embedded user's `username` in this field.
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=userId")
    private String userId;

    @JsonCreator
    public ListWorkflowsRequest(
            Optional<? extends String> integration,
            String userId) {
        Utils.checkNotNull(integration, "integration");
        Utils.checkNotNull(userId, "userId");
        this.integration = integration;
        this.userId = userId;
    }
    
    public ListWorkflowsRequest(
            String userId) {
        this(Optional.empty(), userId);
    }

    /**
     * This parameter allows you to filter workflows based on the name of the integration you're looking for. For example, if you were looking for a Shopify integration, specify shopify
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<String> integration() {
        return (Optional<String>) integration;
    }

    /**
     * The Id of the user you want to lookup. Returned from the Create User endpoint. Note: you can also use the Embedded user's `username` in this field.
     */
    @JsonIgnore
    public String userId() {
        return userId;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * This parameter allows you to filter workflows based on the name of the integration you're looking for. For example, if you were looking for a Shopify integration, specify shopify
     */
    public ListWorkflowsRequest withIntegration(String integration) {
        Utils.checkNotNull(integration, "integration");
        this.integration = Optional.ofNullable(integration);
        return this;
    }

    /**
     * This parameter allows you to filter workflows based on the name of the integration you're looking for. For example, if you were looking for a Shopify integration, specify shopify
     */
    public ListWorkflowsRequest withIntegration(Optional<? extends String> integration) {
        Utils.checkNotNull(integration, "integration");
        this.integration = integration;
        return this;
    }

    /**
     * The Id of the user you want to lookup. Returned from the Create User endpoint. Note: you can also use the Embedded user's `username` in this field.
     */
    public ListWorkflowsRequest withUserId(String userId) {
        Utils.checkNotNull(userId, "userId");
        this.userId = userId;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ListWorkflowsRequest other = (ListWorkflowsRequest) o;
        return 
            java.util.Objects.deepEquals(this.integration, other.integration) &&
            java.util.Objects.deepEquals(this.userId, other.userId);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            integration,
            userId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ListWorkflowsRequest.class,
                "integration", integration,
                "userId", userId);
    }
    
    public final static class Builder {
 
        private Optional<? extends String> integration = Optional.empty();
 
        private String userId;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * This parameter allows you to filter workflows based on the name of the integration you're looking for. For example, if you were looking for a Shopify integration, specify shopify
         */
        public Builder integration(String integration) {
            Utils.checkNotNull(integration, "integration");
            this.integration = Optional.ofNullable(integration);
            return this;
        }

        /**
         * This parameter allows you to filter workflows based on the name of the integration you're looking for. For example, if you were looking for a Shopify integration, specify shopify
         */
        public Builder integration(Optional<? extends String> integration) {
            Utils.checkNotNull(integration, "integration");
            this.integration = integration;
            return this;
        }

        /**
         * The Id of the user you want to lookup. Returned from the Create User endpoint. Note: you can also use the Embedded user's `username` in this field.
         */
        public Builder userId(String userId) {
            Utils.checkNotNull(userId, "userId");
            this.userId = userId;
            return this;
        }
        
        public ListWorkflowsRequest build() {
            return new ListWorkflowsRequest(
                integration,
                userId);
        }
    }
}

