/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.core.type.TypeReference;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Optional;
import java.util.stream.Stream;
import org.openapis.openapi.models.errors.SDKError;
import org.openapis.openapi.utils.LazySingletonValue;
import org.openapis.openapi.utils.Utils;
import org.openapitools.jackson.nullable.JsonNullable;


public class ListWorkflowsRequestBuilder {

    private Optional<? extends String> integration = Optional.empty();
    private String userId;
    private final SDKMethodInterfaces.MethodCallListWorkflows sdk;

    public ListWorkflowsRequestBuilder(SDKMethodInterfaces.MethodCallListWorkflows sdk) {
        this.sdk = sdk;
    }
                
    public ListWorkflowsRequestBuilder integration(String integration) {
        Utils.checkNotNull(integration, "integration");
        this.integration = Optional.of(integration);
        return this;
    }

    public ListWorkflowsRequestBuilder integration(Optional<? extends String> integration) {
        Utils.checkNotNull(integration, "integration");
        this.integration = integration;
        return this;
    }

    public ListWorkflowsRequestBuilder userId(String userId) {
        Utils.checkNotNull(userId, "userId");
        this.userId = userId;
        return this;
    }

    public ListWorkflowsResponse call() throws Exception {

        return sdk.listWorkflows(
            integration,
            userId);
    }
}
