/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.core.type.TypeReference;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Optional;
import java.util.stream.Stream;
import org.openapis.openapi.models.errors.SDKError;
import org.openapis.openapi.utils.LazySingletonValue;
import org.openapis.openapi.utils.Utils;
import org.openapitools.jackson.nullable.JsonNullable;


public class ListUsersByWorkflowidRequestBuilder {

    private String workflowId;
    private Optional<? extends String> userId = Optional.empty();
    private final SDKMethodInterfaces.MethodCallListUsersByWorkflowid sdk;

    public ListUsersByWorkflowidRequestBuilder(SDKMethodInterfaces.MethodCallListUsersByWorkflowid sdk) {
        this.sdk = sdk;
    }

    public ListUsersByWorkflowidRequestBuilder workflowId(String workflowId) {
        Utils.checkNotNull(workflowId, "workflowId");
        this.workflowId = workflowId;
        return this;
    }
                
    public ListUsersByWorkflowidRequestBuilder userId(String userId) {
        Utils.checkNotNull(userId, "userId");
        this.userId = Optional.of(userId);
        return this;
    }

    public ListUsersByWorkflowidRequestBuilder userId(Optional<? extends String> userId) {
        Utils.checkNotNull(userId, "userId");
        this.userId = userId;
        return this;
    }

    public ListUsersByWorkflowidResponse call() throws Exception {

        return sdk.listUsersByWorkflowid(
            workflowId,
            userId);
    }
}
