/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.core.type.TypeReference;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Optional;
import java.util.stream.Stream;
import org.openapis.openapi.models.errors.SDKError;
import org.openapis.openapi.utils.LazySingletonValue;
import org.openapis.openapi.utils.Utils;
import org.openapitools.jackson.nullable.JsonNullable;


public class ListAllUsersRequestBuilder {

    private Optional<? extends String> parentWorkflowId = Optional.empty();
    private final SDKMethodInterfaces.MethodCallListAllUsers sdk;

    public ListAllUsersRequestBuilder(SDKMethodInterfaces.MethodCallListAllUsers sdk) {
        this.sdk = sdk;
    }
                
    public ListAllUsersRequestBuilder parentWorkflowId(String parentWorkflowId) {
        Utils.checkNotNull(parentWorkflowId, "parentWorkflowId");
        this.parentWorkflowId = Optional.of(parentWorkflowId);
        return this;
    }

    public ListAllUsersRequestBuilder parentWorkflowId(Optional<? extends String> parentWorkflowId) {
        Utils.checkNotNull(parentWorkflowId, "parentWorkflowId");
        this.parentWorkflowId = parentWorkflowId;
        return this;
    }

    public ListAllUsersResponse call() throws Exception {

        return sdk.listAllUsers(
            parentWorkflowId);
    }
}
