/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;
/**
 * RerunWorkfowResponseBody - 200
 */

public class RerunWorkfowResponseBody {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("message")
    private Optional<? extends String> message;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("executionUuid")
    private Optional<? extends String> executionUuid;

    @JsonCreator
    public RerunWorkfowResponseBody(
            @JsonProperty("message") Optional<? extends String> message,
            @JsonProperty("executionUuid") Optional<? extends String> executionUuid) {
        Utils.checkNotNull(message, "message");
        Utils.checkNotNull(executionUuid, "executionUuid");
        this.message = message;
        this.executionUuid = executionUuid;
    }
    
    public RerunWorkfowResponseBody() {
        this(Optional.empty(), Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<String> message() {
        return (Optional<String>) message;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<String> executionUuid() {
        return (Optional<String>) executionUuid;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public RerunWorkfowResponseBody withMessage(String message) {
        Utils.checkNotNull(message, "message");
        this.message = Optional.ofNullable(message);
        return this;
    }

    public RerunWorkfowResponseBody withMessage(Optional<? extends String> message) {
        Utils.checkNotNull(message, "message");
        this.message = message;
        return this;
    }

    public RerunWorkfowResponseBody withExecutionUuid(String executionUuid) {
        Utils.checkNotNull(executionUuid, "executionUuid");
        this.executionUuid = Optional.ofNullable(executionUuid);
        return this;
    }

    public RerunWorkfowResponseBody withExecutionUuid(Optional<? extends String> executionUuid) {
        Utils.checkNotNull(executionUuid, "executionUuid");
        this.executionUuid = executionUuid;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RerunWorkfowResponseBody other = (RerunWorkfowResponseBody) o;
        return 
            java.util.Objects.deepEquals(this.message, other.message) &&
            java.util.Objects.deepEquals(this.executionUuid, other.executionUuid);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            message,
            executionUuid);
    }
    
    @Override
    public String toString() {
        return Utils.toString(RerunWorkfowResponseBody.class,
                "message", message,
                "executionUuid", executionUuid);
    }
    
    public final static class Builder {
 
        private Optional<? extends String> message = Optional.empty();
 
        private Optional<? extends String> executionUuid = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder message(String message) {
            Utils.checkNotNull(message, "message");
            this.message = Optional.ofNullable(message);
            return this;
        }

        public Builder message(Optional<? extends String> message) {
            Utils.checkNotNull(message, "message");
            this.message = message;
            return this;
        }

        public Builder executionUuid(String executionUuid) {
            Utils.checkNotNull(executionUuid, "executionUuid");
            this.executionUuid = Optional.ofNullable(executionUuid);
            return this;
        }

        public Builder executionUuid(Optional<? extends String> executionUuid) {
            Utils.checkNotNull(executionUuid, "executionUuid");
            this.executionUuid = executionUuid;
            return this;
        }
        
        public RerunWorkfowResponseBody build() {
            return new RerunWorkfowResponseBody(
                message,
                executionUuid);
        }
    }
}

