/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;
import org.openapis.openapi.utils.Utils;

public class RunWorkflowRequestBody {

    /**
     * The name of the workflow to run.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("workflowName")
    private Optional<? extends String> workflowName;

    /**
     * The Id of the workflow to activate. If you pass this parameter, then `workflowName` is not required.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("workflowId")
    private Optional<? extends String> workflowId;

    /**
     * The Id of the user you want to lookup. Returned from the Create User endpoint. Note: you can also use the Embedded user's `username` in this field.
     */
    @JsonProperty("userId")
    private String userId;

    /**
     * The key-value pairs you want to send as defined in the webhook trigger. This data will be used in expressions during the workflow execution.
     */
    @JsonProperty("data")
    private String data;

    @JsonCreator
    public RunWorkflowRequestBody(
            @JsonProperty("workflowName") Optional<? extends String> workflowName,
            @JsonProperty("workflowId") Optional<? extends String> workflowId,
            @JsonProperty("userId") String userId,
            @JsonProperty("data") String data) {
        Utils.checkNotNull(workflowName, "workflowName");
        Utils.checkNotNull(workflowId, "workflowId");
        Utils.checkNotNull(userId, "userId");
        Utils.checkNotNull(data, "data");
        this.workflowName = workflowName;
        this.workflowId = workflowId;
        this.userId = userId;
        this.data = data;
    }
    
    public RunWorkflowRequestBody(
            String userId,
            String data) {
        this(Optional.empty(), Optional.empty(), userId, data);
    }

    /**
     * The name of the workflow to run.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<String> workflowName() {
        return (Optional<String>) workflowName;
    }

    /**
     * The Id of the workflow to activate. If you pass this parameter, then `workflowName` is not required.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<String> workflowId() {
        return (Optional<String>) workflowId;
    }

    /**
     * The Id of the user you want to lookup. Returned from the Create User endpoint. Note: you can also use the Embedded user's `username` in this field.
     */
    @JsonIgnore
    public String userId() {
        return userId;
    }

    /**
     * The key-value pairs you want to send as defined in the webhook trigger. This data will be used in expressions during the workflow execution.
     */
    @JsonIgnore
    public String data() {
        return data;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * The name of the workflow to run.
     */
    public RunWorkflowRequestBody withWorkflowName(String workflowName) {
        Utils.checkNotNull(workflowName, "workflowName");
        this.workflowName = Optional.ofNullable(workflowName);
        return this;
    }

    /**
     * The name of the workflow to run.
     */
    public RunWorkflowRequestBody withWorkflowName(Optional<? extends String> workflowName) {
        Utils.checkNotNull(workflowName, "workflowName");
        this.workflowName = workflowName;
        return this;
    }

    /**
     * The Id of the workflow to activate. If you pass this parameter, then `workflowName` is not required.
     */
    public RunWorkflowRequestBody withWorkflowId(String workflowId) {
        Utils.checkNotNull(workflowId, "workflowId");
        this.workflowId = Optional.ofNullable(workflowId);
        return this;
    }

    /**
     * The Id of the workflow to activate. If you pass this parameter, then `workflowName` is not required.
     */
    public RunWorkflowRequestBody withWorkflowId(Optional<? extends String> workflowId) {
        Utils.checkNotNull(workflowId, "workflowId");
        this.workflowId = workflowId;
        return this;
    }

    /**
     * The Id of the user you want to lookup. Returned from the Create User endpoint. Note: you can also use the Embedded user's `username` in this field.
     */
    public RunWorkflowRequestBody withUserId(String userId) {
        Utils.checkNotNull(userId, "userId");
        this.userId = userId;
        return this;
    }

    /**
     * The key-value pairs you want to send as defined in the webhook trigger. This data will be used in expressions during the workflow execution.
     */
    public RunWorkflowRequestBody withData(String data) {
        Utils.checkNotNull(data, "data");
        this.data = data;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RunWorkflowRequestBody other = (RunWorkflowRequestBody) o;
        return 
            java.util.Objects.deepEquals(this.workflowName, other.workflowName) &&
            java.util.Objects.deepEquals(this.workflowId, other.workflowId) &&
            java.util.Objects.deepEquals(this.userId, other.userId) &&
            java.util.Objects.deepEquals(this.data, other.data);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            workflowName,
            workflowId,
            userId,
            data);
    }
    
    @Override
    public String toString() {
        return Utils.toString(RunWorkflowRequestBody.class,
                "workflowName", workflowName,
                "workflowId", workflowId,
                "userId", userId,
                "data", data);
    }
    
    public final static class Builder {
 
        private Optional<? extends String> workflowName = Optional.empty();
 
        private Optional<? extends String> workflowId = Optional.empty();
 
        private String userId;
 
        private String data;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The name of the workflow to run.
         */
        public Builder workflowName(String workflowName) {
            Utils.checkNotNull(workflowName, "workflowName");
            this.workflowName = Optional.ofNullable(workflowName);
            return this;
        }

        /**
         * The name of the workflow to run.
         */
        public Builder workflowName(Optional<? extends String> workflowName) {
            Utils.checkNotNull(workflowName, "workflowName");
            this.workflowName = workflowName;
            return this;
        }

        /**
         * The Id of the workflow to activate. If you pass this parameter, then `workflowName` is not required.
         */
        public Builder workflowId(String workflowId) {
            Utils.checkNotNull(workflowId, "workflowId");
            this.workflowId = Optional.ofNullable(workflowId);
            return this;
        }

        /**
         * The Id of the workflow to activate. If you pass this parameter, then `workflowName` is not required.
         */
        public Builder workflowId(Optional<? extends String> workflowId) {
            Utils.checkNotNull(workflowId, "workflowId");
            this.workflowId = workflowId;
            return this;
        }

        /**
         * The Id of the user you want to lookup. Returned from the Create User endpoint. Note: you can also use the Embedded user's `username` in this field.
         */
        public Builder userId(String userId) {
            Utils.checkNotNull(userId, "userId");
            this.userId = userId;
            return this;
        }

        /**
         * The key-value pairs you want to send as defined in the webhook trigger. This data will be used in expressions during the workflow execution.
         */
        public Builder data(String data) {
            Utils.checkNotNull(data, "data");
            this.data = data;
            return this;
        }
        
        public RunWorkflowRequestBody build() {
            return new RunWorkflowRequestBody(
                workflowName,
                workflowId,
                userId,
                data);
        }
    }
}

