/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package org.openapis.openapi;

import org.openapis.openapi.utils.Hook.SdkInitData;
import org.openapis.openapi.utils.HTTPClient;
import org.openapis.openapi.utils.RetryConfig;
import org.openapis.openapi.models.components.Security;
import java.util.Optional;

class SDKConfiguration {
    public SecuritySource securitySource;
    
    public Optional<SecuritySource> securitySource() {
        return Optional.ofNullable(securitySource);
    }
    public HTTPClient defaultClient;
      public String serverUrl;
    public int serverIdx = 0;
    public String language = "java";
    public String openapiDocVersion = "4.0";
    public String sdkVersion = "0.0.5";
    public String genVersion = "2.338.1";
    public String userAgent = "speakeasy-sdk/java 0.0.5 2.338.1 4.0 org.openapis.openapi";

    private org.openapis.openapi.utils.Hooks _hooks = new org.openapis.openapi.utils.Hooks();

    public org.openapis.openapi.utils.Hooks hooks() {
        return _hooks;
    }

    public void setHooks(org.openapis.openapi.utils.Hooks hooks) {
        this._hooks = hooks;
    }

    /** 
     * Initializes state (for example hooks).
     **/
    public void initialize() {

    }

    
    
    public Optional<RetryConfig> retryConfig = Optional.empty();
}
